name = "test-worker2"
main = "src/index.ts"
compatibility_date = "2023-06-29"
route = "jacobmgevans.com/test"
usage_model = "bundled"
env = {}

[[migrations]]
tag = "v2"
new_classes = ["Durabilities"]

[triggers]
crons = []

[vars]
ANOTHER = "thing"
SOMETHING = "asdasdfasdf"

[[durable_objects.bindings]]
name = "DURABLE_TEST"
class_name = "Durability"
